### ISSUE TITLE
Name clash with python intercom

### ISSUE THREAD

**Issue by seocam** [kencochrane/django-intercom#20]
I was going to submit a PR adding a Intercom email backend but I had issues due to a name clash.
Both django-intercom (yours) and python-intercom libs use the same `intercom` namespace.

**Comment by kencochrane** [comment]
What do you recommend? This library is over 4 years old, and this is the first time someone mentioned a problem.

**Comment by seocam** [comment]
One possibility would be to rename the `django-intercom/intercom` directory to `django-intercom/django_intercom/` or `django-intercom/dj_intercom/`. In that case you would have to do a new major release.

In case you want to check that's what I would like to add to django-intercom: https://github.com/CraveFood/django-intercom-email-backend

I can see a whole new set of features that could be implemented in django-intercom with the use of python-intercom. For instance would great to have a middleware or something to create a user in intercom and store the intercom user id in the db using django orm. That would help to track if the user has changed his email address and update the intercom account.

Another option would be to re-implement the functionalities of python-intercom. Yet other option would be to just copy python-intercom source code and distribute it together with django-intercom (`requests` does that with `chardet` and `urllib3` – https://github.com/kennethreitz/requests/tree/master/requests/packages).

All options have their advantages and drawbacks...

**Comment by kccheung** [comment]
#32

**Comment by kencochrane** [comment]
This has been fixed with 0.1.0
