### ISSUE TITLE
Session data would be useful in the user and company contexts

### ISSUE THREAD

**Issue by eraad** [kencochrane/django-intercom#21]
Hi!

I'm using data from `request.session` to populate the `company` object in this manner:

https://github.com/datil/django-intercom/commit/2186398014037e39d75900701d9313a0eb96c914

Do you think this may be useful to other users? My main concern is that adding `session` to the `company_data` function looks like a breaking change for the library.

What are your thoughts on this?

**Comment by kencochrane** [comment]
To be honest, I'm not sure. This is the first I have heard of it, so no one else is requesting it. Because of this, I would prefer to not include session to the company_data at this time. This opinion might change if there are more requests in the future.

**Comment by eraad** [comment]
Thanks for the quick response. Got it. Will test it and keep an eye on the project.
