### ISSUE TITLE
'int' object has no attribute 'encode'

### ISSUE THREAD

**Issue by christippett** [kencochrane/django-intercom#27]
Hi,

Your latest commit has caused a regression when it comes to using identify verification.

Previously `hmac_value` was defined as `hmac_value = str(user_id) if user_id else email`. The latest commit now has it as `hmac_value = user_id if user_id else email`.

`user_id` needs to be a string before it can be encoded, otherwise the above error is returned.

**Comment by rosscdh** [comment]
Sorry, would have fixed! Thanks for the catch!

**Comment by kencochrane** [comment]
Thanks for noticing. If someone has a minute could they submit a PR? I’m working off my phone right now so I wouldn’t be able to get to it until tonight at the earliest.

**Comment by rosscdh** [comment]
I think its already been fixed in master. #26

**Comment by rosscdh** [comment]
very strange.. I've updated the feature branch https://github.com/kencochrane/django-intercom/pull/28/commits/c4a15ff7164c42696c6af8b6fd4b6101239fb542 but not reflecting in the PR

**Comment by kencochrane** [comment]
Should be fixed in #29
