### ISSUE TITLE
TypeError: 'bool' object is not callable

### ISSUE THREAD

**Issue by AnArchkoleptik** [kencochrane/django-intercom#34]
Hi! 

I tried to use this package for a project but I had an error : at the condition `TypeError: 'bool' object is not callable`

I just changed this and it worked:
`if INTERCOM_APPID and request.user and request.user.is_authenticated():` 
**->** `if INTERCOM_APPID and request.user and request.user.is_authenticated:`
*(django_intercom/templatetags/intercom.py - l.77)*

Hope it helps someone!

**Comment by kencochrane** [comment]
@AnArchkoleptik thanks for the report, if you have time, could you submit a Pull Request with the change, so that I can merge and fix the error, that would be very helpful. Thank you!

**Comment by AnArchkoleptik** [comment]
@kencochrane You're welcome!
I tried to clone, create a new branch, commit and push, but at the push, I have a message telling me I don't have the permission to do that. Did I do something wrong?

**Comment by kencochrane** [comment]
Thanks, you are on the right track, you just missed one step. You will need to fork my repo, and then push your branch to your fork, where you will have permission.

Once the branch is on your fork, you can open a PR from your fork to my repo.

Hope that helps, if you have any questions, please let me know.

**Comment by AnArchkoleptik** [comment]
Cool! 
I did just what you told me to do, and it seemed to work. Thanks for explanations!

**Comment by kencochrane** [comment]
Thanks for contributing!, I just merged your PR.

**Comment by AnArchkoleptik** [comment]
My pleasure, and thank you for making this package!
